import type { NextPage } from 'next'
import Head from 'next/head'
import Link from 'next/link'
import styles from '../styles/Home.module.css'
import generateRandomString from '../helpers/generateRandomString';

const Home: NextPage = () => {

  const storeNonce = () => {
    const nonceString = generateRandomString(10);
    localStorage.setItem(nonceString, JSON.stringify({redirectUrl: '/landing-page'}))
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Link href="/api/auth/login" onClick={storeNonce}>
        <button>
          Login
        </button>
      </Link>
     
      
    </div>
  )
}

export default Home
